# Generated by Django 5.0.6 on 2024-07-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('Repair', 'Repair'), ('Installation', 'Installation'), ('Maintenance', 'Maintenance'), ('Other', 'Other')], max_length=50)),
                ('details', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='service_requests/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
